//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacketCaptureAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacketCaptureAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of the packet capture completed successfully!.
        /// </summary>
        internal static string AnalysisOfThePacketCaptureCompletedSuccessfully {
            get {
                return ResourceManager.GetString("AnalysisOfThePacketCaptureCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of the packet capture failed!!!.
        /// </summary>
        internal static string AnalysisOfThePacketCaptureFailed {
            get {
                return ResourceManager.GetString("AnalysisOfThePacketCaptureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst Analysis.
        /// </summary>
        internal static string BurstAnalysis {
            get {
                return ResourceManager.GetString("BurstAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected Packet Capture.
        /// </summary>
        internal static string ClearSelectedPacketCapture {
            get {
                return ResourceManager.GetString("ClearSelectedPacketCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Information.
        /// </summary>
        internal static string DebugInformation {
            get {
                return ResourceManager.GetString("DebugInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open the output file?.
        /// </summary>
        internal static string DoYouWantToOpenTheOutputFile {
            get {
                return ResourceManager.GetString("DoYouWantToOpenTheOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Information Events.
        /// </summary>
        internal static string EnableInformationEvents {
            get {
                return ResourceManager.GetString("EnableInformationEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency Analysis.
        /// </summary>
        internal static string LatencyAnalysis {
            get {
                return ResourceManager.GetString("LatencyAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Memory Usage (Potentially Necessary For Very Large Files).
        /// </summary>
        internal static string MinimizeMemoryUsage {
            get {
                return ResourceManager.GetString("MinimizeMemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA Sniffer (DOS).
        /// </summary>
        internal static string NASnifferDOS {
            get {
                return ResourceManager.GetString("NASnifferDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selected Packet Capture.
        /// </summary>
        internal static string OpenSelectedPacketCapture {
            get {
                return ResourceManager.GetString("OpenSelectedPacketCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Additional Information.
        /// </summary>
        internal static string OutputAdditionalInformation {
            get {
                return ResourceManager.GetString("OutputAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Histogram.
        /// </summary>
        internal static string OutputHistogram {
            get {
                return ResourceManager.GetString("OutputHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Time Additional Information.
        /// </summary>
        internal static string OutputTimeAdditionalInformation {
            get {
                return ResourceManager.GetString("OutputTimeAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Time Histogram.
        /// </summary>
        internal static string OutputTimeHistogram {
            get {
                return ResourceManager.GetString("OutputTimeHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Timestamp Additional Information.
        /// </summary>
        internal static string OutputTimestampAdditionalInformation {
            get {
                return ResourceManager.GetString("OutputTimestampAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Timestamp Histogram.
        /// </summary>
        internal static string OutputTimestampHistogram {
            get {
                return ResourceManager.GetString("OutputTimestampHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Capture Analyser.
        /// </summary>
        internal static string PacketCaptureAnalyser {
            get {
                return ResourceManager.GetString("PacketCaptureAnalyser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Captures (*.pcapng,*.pcap,*.libpcap,*.enc,*.cap,*.ntar)|*.pcapng;*.pcap;*.libpcap;*.enc;*.cap;*.ntar.
        /// </summary>
        internal static string PacketCapturesFilter {
            get {
                return ResourceManager.GetString("PacketCapturesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCAP (libpcap/tcpdump).
        /// </summary>
        internal static string PCAP {
            get {
                return ResourceManager.GetString("PCAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCAP Next Generation.
        /// </summary>
        internal static string PCAPNextGeneration {
            get {
                return ResourceManager.GetString("PCAPNextGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform.
        /// </summary>
        internal static string Perform {
            get {
                return ResourceManager.GetString("Perform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect To Output.
        /// </summary>
        internal static string RedirectToOutput {
            get {
                return ResourceManager.GetString("RedirectToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Analysis On Selected Packet Capture.
        /// </summary>
        internal static string RunAnalysisOnSelectedPacketCapture {
            get {
                return ResourceManager.GetString("RunAnalysisOnSelectedPacketCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Packet Capture.
        /// </summary>
        internal static string SelectedPacketCapture {
            get {
                return ResourceManager.GetString("SelectedPacketCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Packet Capture.
        /// </summary>
        internal static string SelectPacketCapture {
            get {
                return ResourceManager.GetString("SelectPacketCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Packet Capture For Analysis.
        /// </summary>
        internal static string SelectPacketCaptureForAnalysis {
            get {
                return ResourceManager.GetString("SelectPacketCaptureForAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Analysis.
        /// </summary>
        internal static string TimeAnalysis {
            get {
                return ResourceManager.GetString("TimeAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Alternative Sequence Number (For Legacy Recordings).
        /// </summary>
        internal static string UseAlternativeSequenceNumber {
            get {
                return ResourceManager.GetString("UseAlternativeSequenceNumber", resourceCulture);
            }
        }
    }
}
